### ISSUE TITLE
v4l2 (hardware decoding) driver bug

### ISSUE THREAD

**Issue by ItsVixano** [ItsVixano/android_kernel_xiaomi_msm8953#1]
1. Download instagram
2. Go to reels
3. Scroll to video

```
[ 1673.703845] subsys-pil-tz 1de0000.qcom,venus: venus: Brought out of reset
[ 1673.771240] msm_vidc:  err: HFI_EVENT_SESSION_ERROR
[ 1673.771269] msm_vidc: warn: Session error received for session 0000000000000000
[ 1673.771274] msm_vidc: warn: Unknown session error (-2147483648) for 0000000000000000
[ 1673.773727] msm_vidc:  err: Core is in bad state can't change the state
[ 1673.773733] msm_vidc:  err: Failed to move from state: 17 to 9
[ 1673.773736] msm_vidc:  err: Failed to move inst: 0000000000000000 to start done state
[ 1673.773740] msm_vidc:  err: Streamon failed on: 10 capability for inst: 0000000000000000
[ 1673.773800] ------------[ cut here ]------------
[ 1673.773812] WARNING: CPU: 7 PID: 10600 at drivers/media/v4l2-core/videobuf2-core.c:1346 vb2_start_streaming+0xcc/0x120
[ 1673.773815] Modules linked in:
[ 1673.773825] CPU: 7 PID: 10600 Comm: VideoDecMsgThre Tainted: G        W       4.9.227-lineageos-g8796c9aea #2
[ 1673.773827] Hardware name: Qualcomm Technologies, Inc. MSM8953 + PMI8950 QRD SKU3 (DT)
[ 1673.773830] task: 000000001b9a33c1 task.stack: 00000000f59c55c8
[ 1673.773833] PC is at vb2_start_streaming+0xcc/0x120
[ 1673.773836] LR is at vb2_start_streaming+0x5c/0x120
[ 1673.773838] pc : [<ffffff8008926a58>] lr : [<ffffff80089269e8>] pstate: 80400145
[ 1673.773839] sp : ffffffc07f05ba10
[ 1673.773841] x29: ffffffc07f05ba10 x28: 0000000000000000
[ 1673.773844] x27: 0000000000000000 x26: ffffff80092b7170
[ 1673.773847] x25: ffffffc0802e6ec8 x24: ffffffc0a38da600
[ 1673.773849] x23: ffffffc0a38da600 x22: ffffff8009f40000
[ 1673.773852] x21: ffffffc0802e6420 x20: 00000000ffffffea
[ 1673.773855] x19: ffffffc0802e6188 x18: 00000000000026d3
[ 1673.773857] x17: ffffff800a10b000 x16: 0000000000000000
[ 1673.773860] x15: 000000000000005c x14: 00000000000000c6
[ 1673.773863] x13: 0000000000000000 x12: 0000000000000004
[ 1673.773865] x11: 0000000000000001 x10: 0000000000000007
[ 1673.773868] x9 : 0000000000000070 x8 : 0000000000000001
[ 1673.773870] x7 : 0000000000000000 x6 : ffffffc0f1cddcb8
[ 1673.773873] x5 : 000000000000006c x4 : 000000000000000a
[ 1673.773876] x3 : 0000000000003030 x2 : 0000000000000000
[ 1673.773879] x1 : 0000000000000140 x0 : 00000000ffffffea
[ 1673.773882] \x0aPC: 0xffffff8008926a18:
[ 1673.773883] 6a18  91011821 97dff8b4 b942ae68 350001a8 f9415a68 910ac269 eb08013f 54000080
[ 1673.773893] 6a38  d4210000 14000002 2a1f03f4 2a1403e0 a9424ff4 a94157f6 a8c37bfd d65f03c0
[ 1673.773902] 6a58  d4210000 b9429268 340001e8 aa1f03f5 91024276 14000004 910006b5 eb2842bf
[ 1673.773910] 6a78  54000122 f8757ac0 b941a009 7100153f 54ffff41 52800061 97fffbbf b9429268
[ 1673.773920] \x0aLR: 0xffffff80089269a8:
[ 1673.773920] 69a8  eb1402bf 540000c0 d106a280 97fffc7e f9400294 eb1402bf 54ffff81 394c8268
[ 1673.773929] 69c8  f9401a69 321f0108 390c8268 f9401d28 b4000348 b942ae61 aa1303e0 d63f0100
[ 1673.773937] 69e8  2a0003f4 340002c0 d000c3c8 394c8269 b94cb508 121e7929 7100051f 390c8269
[ 1673.773946] 6a08  540000cb b0007940 900079e1 910f6000 91011821 97dff8b4 b942ae68 350001a8
[ 1673.773955] \x0aSP: 0xffffffc07f05b9d0:
[ 1673.773956] b9d0  089269e8 ffffff80 7f05ba10 ffffffc0 08926a58 ffffff80 80400145 00000000
[ 1673.773964] b9f0  09f40000 ffffff80 802e6420 ffffffc0 ffffffff 0000007f 802e6188 ffffffc0
[ 1673.773973] ba10  7f05ba40 ffffffc0 08927178 ffffff80 09f40000 ffffff80 802e64c0 ffffffc0
[ 1673.773981] ba30  00000000 00000000 802e6188 ffffffc0 7f05ba60 ffffffc0 08928cb8 ffffff80
[ 1673.773991] ---[ end trace caa7bc621201b566 ]---
[ 1673.773993] Call trace:
[ 1673.773996] Exception stack(0xffffffc07f05b8b0 to 0xffffffc07f05b9e0)
[ 1673.774000] b8a0:                                   000000000000003d 0000000080400145
[ 1673.774003] b8c0: ffffff8008926a58 00000000123ed000 0000007fffffffff ffffffc0802e6188
[ 1673.774006] b8e0: 00000000ffffffea 0000000000000140 0000000000000000 0000000000003030
[ 1673.774008] b900: 000000000000000a 000000000000006c ffffffc0f1cddcb8 0000000000000000
[ 1673.774011] b920: 0000000000000001 0000000000000070 0000000000000007 0000000000000001
[ 1673.774014] b940: 0000000000000004 0000000000000000 00000000000000c6 000000000000005c
[ 1673.774017] b960: 0000000000000000 ffffff800a10b000 00000000000026d3 ffffffc0802e6188
[ 1673.774020] b980: 00000000ffffffea ffffffc0802e6420 ffffff8009f40000 ffffffc0a38da600
[ 1673.774023] b9a0: ffffffc0a38da600 ffffffc0802e6ec8 ffffff80092b7170 0000000000000000
[ 1673.774026] b9c0: 0000000000000000 ffffffc07f05ba10 ffffff80089269e8 ffffffc07f05ba10
[ 1673.774029] [<0000000020ec6d53>] vb2_start_streaming+0xcc/0x120
[ 1673.774034] [<000000005106189b>] vb2_core_streamon+0x128/0x144
[ 1673.774037] [<0000000026360a28>] vb2_streamon+0x44/0x4c
[ 1673.774042] [<00000000bc79ac6e>] msm_vdec_streamon+0xc0/0x164
[ 1673.774046] [<00000000c0ac365c>] msm_vidc_streamon+0x20/0x40
[ 1673.774049] [<000000003c86dc97>] msm_v4l2_streamon+0x18/0x20
[ 1673.774052] [<00000000c5c8b694>] v4l_streamon+0x20/0x28
[ 1673.774056] [<0000000009bd0680>] __video_do_ioctl+0x128/0x260
[ 1673.774058] [<00000000a818770d>] video_usercopy+0x254/0x5c4
[ 1673.774061] [<000000009fa79a62>] video_ioctl2+0x14/0x1c
[ 1673.774063] [<0000000092b86bee>] v4l2_ioctl+0x9c/0xc4
[ 1673.774066] [<00000000b24bf510>] do_video_ioctl+0xcdc/0x4478
[ 1673.774069] [<00000000b1a53196>] v4l2_compat_ioctl32+0x58/0x90
[ 1673.774074] [<000000009724c68b>] compat_SyS_ioctl+0x128/0x22c
[ 1673.774078] [<0000000059f1b9d2>] __sys_trace_return+0x0/0x4
[ 1673.774100] msm_vidc:  err: streamon failed on port: 10
[ 1673.794922] msm_vidc: warn: msm_comm_generate_session_error
[ 1673.794927] msm_vidc: warn: Got a response for an inactive session
[ 1673.794937] msm_vidc:  err: Core 0000000000000000 and inst 0000000000000000 are in bad state
[ 1673.795224] msm_vidc:  err: Core is in bad state can't change the state
[ 1673.795229] msm_vidc:  err: Failed to move from state: 17 to 13
[ 1673.795231] msm_vidc:  err: Failed to move inst: 0000000000000000 to start done state
[ 1673.795274] msm_vidc:  err: Failed to move inst: 0000000000000000, cap = 9 to state: 13
[ 1673.797042] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1673.797047] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1673.797049] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1673.797051] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1673.797053] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1673.797055] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1673.804723] msm_vidc: info: Closed video instance: 0000000000000000
[ 1673.955521] msm_vidc: info: Opening video instance: 0000000000000000, 1
[ 1673.990259] msm_vidc:  err: HFI_EVENT_SESSION_ERROR
[ 1673.990282] msm_vidc: warn: Session error received for session 0000000000000000
[ 1673.990285] msm_vidc: warn: Unknown session error (-2147483648) for 0000000000000000
[ 1673.990435] msm_vidc:  err: Load resource response from FW : 0x80000000
[ 1673.990438] msm_vidc: warn: msm_comm_generate_session_error
[ 1673.990441] msm_vidc: warn: Session error received for session 0000000000000000
[ 1673.990442] msm_vidc: warn: Unknown session error (-2147483648) for 0000000000000000
[ 1673.991892] msm_vidc:  err: State not recognized
[ 1673.991896] msm_vidc:  err: Failed to move from state: 17 to 9
[ 1673.991900] msm_vidc:  err: Failed to move inst: 0000000000000000 to start done state
[ 1673.991902] msm_vidc:  err: Streamon failed on: 10 capability for inst: 0000000000000000
[ 1673.991943] ------------[ cut here ]------------
[ 1673.991953] WARNING: CPU: 4 PID: 10612 at drivers/media/v4l2-core/videobuf2-core.c:1346 vb2_start_streaming+0xcc/0x120
[ 1673.991954] Modules linked in:
[ 1673.991961] CPU: 4 PID: 10612 Comm: VideoDecMsgThre Tainted: G        W       4.9.227-lineageos-g8796c9aea #2
[ 1673.991963] Hardware name: Qualcomm Technologies, Inc. MSM8953 + PMI8950 QRD SKU3 (DT)
[ 1673.991966] task: 0000000013534a07 task.stack: 000000006ad95cf3
[ 1673.991970] PC is at vb2_start_streaming+0xcc/0x120
[ 1673.991972] LR is at vb2_start_streaming+0x5c/0x120
[ 1673.991975] pc : [<ffffff8008926a58>] lr : [<ffffff80089269e8>] pstate: 80400145
[ 1673.991976] sp : ffffffc08247fa10
[ 1673.991977] x29: ffffffc08247fa10 x28: 0000000000000000
[ 1673.991980] x27: 0000000000000000 x26: ffffff80092b7170
[ 1673.991983] x25: ffffffc0802e6ec8 x24: ffffffc0a7609e00
[ 1673.991986] x23: ffffffc0a7609e00 x22: ffffff8009f40000
[ 1673.991989] x21: ffffffc0802e6420 x20: 00000000ffffffea
[ 1673.991991] x19: ffffffc0802e6188 x18: 0000000000002755
[ 1673.991994] x17: ffffff800a10b000 x16: 0000000000000000
[ 1673.991996] x15: 000000000000005c x14: 00000000000000c6
[ 1673.991999] x13: 0000000000000000 x12: 0000000000000004
[ 1673.992001] x11: 0000000000000001 x10: 0000000000000007
[ 1673.992004] x9 : 0000000000000070 x8 : 0000000000000001
[ 1673.992007] x7 : 0000000000000000 x6 : ffffffc0f1cdf890
[ 1673.992009] x5 : 000000000000008c x4 : 000000000000000a
[ 1673.992012] x3 : 0000000000003030 x2 : 0000000000000000
[ 1673.992014] x1 : 0000000000000140 x0 : 00000000ffffffea
[ 1673.992017] \x0aPC: 0xffffff8008926a18:
[ 1673.992018] 6a18  91011821 97dff8b4 b942ae68 350001a8 f9415a68 910ac269 eb08013f 54000080
[ 1673.992029] 6a38  d4210000 14000002 2a1f03f4 2a1403e0 a9424ff4 a94157f6 a8c37bfd d65f03c0
[ 1673.992037] 6a58  d4210000 b9429268 340001e8 aa1f03f5 91024276 14000004 910006b5 eb2842bf
[ 1673.992045] 6a78  54000122 f8757ac0 b941a009 7100153f 54ffff41 52800061 97fffbbf b9429268
[ 1673.992054] \x0aLR: 0xffffff80089269a8:
[ 1673.992055] 69a8  eb1402bf 540000c0 d106a280 97fffc7e f9400294 eb1402bf 54ffff81 394c8268
[ 1673.992064] 69c8  f9401a69 321f0108 390c8268 f9401d28 b4000348 b942ae61 aa1303e0 d63f0100
[ 1673.992072] 69e8  2a0003f4 340002c0 d000c3c8 394c8269 b94cb508 121e7929 7100051f 390c8269
[ 1673.992080] 6a08  540000cb b0007940 900079e1 910f6000 91011821 97dff8b4 b942ae68 350001a8
[ 1673.992089] \x0aSP: 0xffffffc08247f9d0:
[ 1673.992090] f9d0  089269e8 ffffff80 8247fa10 ffffffc0 08926a58 ffffff80 80400145 00000000
[ 1673.992098] f9f0  09f40000 ffffff80 802e6420 ffffffc0 ffffffff 0000007f 802e6188 ffffffc0
[ 1673.992107] fa10  8247fa40 ffffffc0 08927178 ffffff80 09f40000 ffffff80 802e64c0 ffffffc0
[ 1673.992115] fa30  00000000 00000000 802e6188 ffffffc0 8247fa60 ffffffc0 08928cb8 ffffff80
[ 1673.992124] ---[ end trace caa7bc621201b567 ]---
[ 1673.992126] Call trace:
[ 1673.992130] Exception stack(0xffffffc08247f8b0 to 0xffffffc08247f9e0)
[ 1673.992133] f8a0:                                   000000000000003d 0000000080400145
[ 1673.992136] f8c0: ffffff8008926a58 00000000123ed000 0000007fffffffff ffffffc0802e6188
[ 1673.992138] f8e0: 00000000ffffffea 0000000000000140 0000000000000000 0000000000003030
[ 1673.992142] f900: 000000000000000a 000000000000008c ffffffc0f1cdf890 0000000000000000
[ 1673.992144] f920: 0000000000000001 0000000000000070 0000000000000007 0000000000000001
[ 1673.992147] f940: 0000000000000004 0000000000000000 00000000000000c6 000000000000005c
[ 1673.992150] f960: 0000000000000000 ffffff800a10b000 0000000000002755 ffffffc0802e6188
[ 1673.992153] f980: 00000000ffffffea ffffffc0802e6420 ffffff8009f40000 ffffffc0a7609e00
[ 1673.992156] f9a0: ffffffc0a7609e00 ffffffc0802e6ec8 ffffff80092b7170 0000000000000000
[ 1673.992158] f9c0: 0000000000000000 ffffffc08247fa10 ffffff80089269e8 ffffffc08247fa10
[ 1673.992162] [<0000000020ec6d53>] vb2_start_streaming+0xcc/0x120
[ 1673.992166] [<000000005106189b>] vb2_core_streamon+0x128/0x144
[ 1673.992169] [<0000000026360a28>] vb2_streamon+0x44/0x4c
[ 1673.992173] [<00000000bc79ac6e>] msm_vdec_streamon+0xc0/0x164
[ 1673.992177] [<00000000c0ac365c>] msm_vidc_streamon+0x20/0x40
[ 1673.992180] [<000000003c86dc97>] msm_v4l2_streamon+0x18/0x20
[ 1673.992184] [<00000000c5c8b694>] v4l_streamon+0x20/0x28
[ 1673.992186] [<0000000009bd0680>] __video_do_ioctl+0x128/0x260
[ 1673.992189] [<00000000a818770d>] video_usercopy+0x254/0x5c4
[ 1673.992192] [<000000009fa79a62>] video_ioctl2+0x14/0x1c
[ 1673.992194] [<0000000092b86bee>] v4l2_ioctl+0x9c/0xc4
[ 1673.992197] [<00000000b24bf510>] do_video_ioctl+0xcdc/0x4478
[ 1673.992200] [<00000000b1a53196>] v4l2_compat_ioctl32+0x58/0x90
[ 1673.992204] [<000000009724c68b>] compat_SyS_ioctl+0x128/0x22c
[ 1673.992209] [<0000000059f1b9d2>] __sys_trace_return+0x0/0x4
[ 1673.992239] msm_vidc:  err: streamon failed on port: 10
[ 1674.017990] msm_vidc:  err: Core 0000000000000000 and inst 0000000000000000 are in bad state
[ 1674.018211] msm_vidc:  err: Core is in bad state can't change the state
[ 1674.018216] msm_vidc:  err: Failed to move from state: 17 to 13
[ 1674.018218] msm_vidc:  err: Failed to move inst: 0000000000000000 to start done state
[ 1674.018261] msm_vidc:  err: Failed to move inst: 0000000000000000, cap = 9 to state: 13
[ 1674.021532] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1674.021537] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1674.021539] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1674.021541] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1674.021543] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1674.021545] msm_vidc:  err: Core 0000000000000000 in bad state, ignoring release output buf
[ 1674.028443] msm_vidc: info: Closed video instance: 0000000000000000
```

**Comment by ItsVixano** [comment]
These logspam on logcat might be also related ig 

```
10-23 15:41:08.946   860 10726 E OMX-VDEC-1080P: Error: Insufficient size allocated for extra-data
```

```
10-23 15:42:02.766   860 11041 E OMX-VDEC-1080P: Failed to qbuf to driver, error Invalid argument
10-23 15:42:02.766   860 11041 E OMX-VDEC-1080P: fill_this_buffer_proxy failure
10-23 15:42:02.766   860 11041 E OMX-VDEC-1080P: Failed to qbuf Input buffer to driver, send ETB back to client
10-23 15:42:02.766   860 11041 E OMX-VDEC-1080P: empty_this_buffer_proxy failure
10-23 15:42:02.766   860 11041 E OMX-VDEC-1080P: Failed to qbuf Input buffer to driver, send ETB back to client
10-23 15:42:02.766   860 11041 E OMX-VDEC-1080P: empty_this_buffer_proxy failure
10-23 15:42:02.769   860 11041 E OMX-VDEC-1080P: fill_this_buffer_proxy failure
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal: Stop failed.
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal: java.lang.IllegalStateException
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at android.media.MediaCodec.native_stop(Native Method)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at android.media.MediaCodec.stop(MediaCodec.java:2338)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.35U.stop(:2)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.35R.A02(:154)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.31M.A0M(:77)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.31L.A0M(:2)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.31M.A0F(:5)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.31L.A0F(:66)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.32m.A0F(:50)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.32m.A0J(:39)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.32m.A0I(:1)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at X.32m.handleMessage(:3431)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at android.os.Looper.loopOnce(Looper.java:201)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at android.os.Looper.loop(Looper.java:288)
10-23 15:42:02.770  9601 11020 E ExoPlayerImplInternal:         at android.os.HandlerThread.run(HandlerThread.java:67)
10-23 15:42:02.778   860  1946 I OMX-VDEC-1080P: omx_vdec::component_deinit() complete
10-23 15:42:02.779   860  1946 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=7
10-23 15:42:02.780   860  1946 I OMX-VDEC-1080P: Video slvp perflock released
```

**Comment by Quallenauge** [comment]
Using an modified version of the 3.18 ```include/uapi/media/msm_media_info.h``` did the trick on first sight!

**Comment by Quallenauge** [comment]
Possible fix: 
https://github.com/Quallenauge/android_kernel_bq_msm8953/commit/4cd17db39c239d71957f1377c9d5f212c5140a84

Rebuilding user space is necessary.

**Comment by ItsVixano** [comment]
> Possible fix: [Quallenauge/android_kernel_bq_msm8953@4cd17db](https://github.com/Quallenauge/android_kernel_bq_msm8953/commit/4cd17db39c239d71957f1377c9d5f212c5140a84)
> 
> Rebuilding user space is necessary.

That's actually the revert of https://github.com/ItsVixano/android_kernel_xiaomi_msm8953/commit/e265d46203a6a01abb9824933dee5641f4aff428 , even tho, seems it didn't done the trick here :(

**Comment by ItsVixano** [comment]
Worked fine on daisy, somehow it didn't rebuild the userspace libs :D

**Comment by teftel1608** [comment]
almost all videos work, but sometimes the video pauses and the quality drops to the minimum.  matlog says unsupported omx config
[omx.txt](https://github.com/ItsVixano/android_kernel_xiaomi_msm8953/files/10148289/omx.txt)
